// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_controlsScreen_screen_init(void)
{
ui_controlsScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_controlsScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_TabView8 = lv_tabview_create(ui_controlsScreen, LV_DIR_TOP, 50);
lv_obj_set_width( ui_TabView8, 800);
lv_obj_set_height( ui_TabView8, 480);
lv_obj_set_align( ui_TabView8, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_TabView8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_TabView8), lv_color_hex(0x2095F6),  LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_TabView8), 255,  LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label26 = lv_label_create(ui_controlsScreen);
lv_obj_set_width( ui_Label26, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label26, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_Label26,"Controls");
lv_obj_set_style_text_font(ui_Label26, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Label26, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Label26, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Label26, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Label26, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Controls = lv_obj_create(ui_controlsScreen);
lv_obj_remove_style_all(ui_Controls);
lv_obj_set_height( ui_Controls, 360);
lv_obj_set_width( ui_Controls, lv_pct(100));
lv_obj_set_x( ui_Controls, 0 );
lv_obj_set_y( ui_Controls, 55 );
lv_obj_set_align( ui_Controls, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_Controls,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_Controls, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_set_scrollbar_mode(ui_Controls, LV_SCROLLBAR_MODE_ON);
lv_obj_set_style_pad_left(ui_Controls, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Controls, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Controls, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Controls, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_controlActionsContainer = lv_obj_create(ui_controlsScreen);
lv_obj_remove_style_all(ui_controlActionsContainer);
lv_obj_set_height( ui_controlActionsContainer, 60);
lv_obj_set_width( ui_controlActionsContainer, lv_pct(100));
lv_obj_set_align( ui_controlActionsContainer, LV_ALIGN_BOTTOM_MID );
lv_obj_clear_flag( ui_controlActionsContainer, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_controlActionsContainer, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_controlActionsContainer, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_controlActionsContainer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_controlActionsContainer, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_abortBtn4 = lv_btn_create(ui_controlActionsContainer);
lv_obj_set_width( ui_abortBtn4, 100);
lv_obj_set_height( ui_abortBtn4, 50);
lv_obj_set_align( ui_abortBtn4, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_add_flag( ui_abortBtn4, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_abortBtn4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_abortBtn4, lv_color_hex(0xEA235F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_abortBtn4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label27 = lv_label_create(ui_abortBtn4);
lv_obj_set_width( ui_Label27, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label27, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label27, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label27,"Back");

ui_addControlBtn = lv_btn_create(ui_controlActionsContainer);
lv_obj_set_width( ui_addControlBtn, 100);
lv_obj_set_height( ui_addControlBtn, 50);
lv_obj_set_align( ui_addControlBtn, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_addControlBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_addControlBtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_addControlLabel1 = lv_label_create(ui_addControlBtn);
lv_obj_set_width( ui_addControlLabel1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_addControlLabel1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_addControlLabel1, LV_ALIGN_CENTER );
lv_label_set_text(ui_addControlLabel1,"Add Control");

lv_obj_add_event_cb(ui_abortBtn4, ui_event_abortBtn4, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_addControlBtn, ui_event_addControlBtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_controlActionsContainer, ui_event_controlActionsContainer, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_controlsScreen, ui_event_controlsScreen, LV_EVENT_ALL, NULL);

}
