// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_generalSettingsScreen_screen_init(void)
{
ui_generalSettingsScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_generalSettingsScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_TabView7 = lv_tabview_create(ui_generalSettingsScreen, LV_DIR_TOP, 50);
lv_obj_set_width( ui_TabView7, 800);
lv_obj_set_height( ui_TabView7, 480);
lv_obj_set_align( ui_TabView7, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_TabView7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_TabView7), lv_color_hex(0x2095F6),  LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_TabView7), 255,  LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label21 = lv_label_create(ui_generalSettingsScreen);
lv_obj_set_width( ui_Label21, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label21, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_Label21,"General settings");
lv_obj_set_style_text_font(ui_Label21, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Label21, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Label21, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Label21, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Label21, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SettingWrap = lv_obj_create(ui_generalSettingsScreen);
lv_obj_set_height( ui_SettingWrap, 480);
lv_obj_set_width( ui_SettingWrap, lv_pct(100));
lv_obj_set_align( ui_SettingWrap, LV_ALIGN_BOTTOM_MID );
lv_obj_clear_flag( ui_SettingWrap, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Container6 = lv_obj_create(ui_SettingWrap);
lv_obj_remove_style_all(ui_Container6);
lv_obj_set_width( ui_Container6, 800);
lv_obj_set_height( ui_Container6, 480);
lv_obj_set_align( ui_Container6, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container6,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_Container6, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_set_scrollbar_mode(ui_Container6, LV_SCROLLBAR_MODE_ON);
lv_obj_set_scroll_dir(ui_Container6, LV_DIR_BOTTOM);

ui_Container7 = lv_obj_create(ui_Container6);
lv_obj_remove_style_all(ui_Container7);
lv_obj_set_height( ui_Container7, 120);
lv_obj_set_width( ui_Container7, lv_pct(33));
lv_obj_set_align( ui_Container7, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_Container7, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Container7, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Container7, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Container7, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_settingsPincode = lv_obj_create(ui_Container7);
lv_obj_set_height( ui_settingsPincode, 110);
lv_obj_set_width( ui_settingsPincode, lv_pct(100));
lv_obj_clear_flag( ui_settingsPincode, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_pinlabel = lv_label_create(ui_settingsPincode);
lv_obj_set_width( ui_pinlabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_pinlabel, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_pinlabel,"PIN code");

ui_settingsPincodeInput = lv_textarea_create(ui_settingsPincode);
lv_obj_set_width( ui_settingsPincodeInput, lv_pct(100));
lv_obj_set_height( ui_settingsPincodeInput, LV_SIZE_CONTENT);   /// 70
lv_obj_set_align( ui_settingsPincodeInput, LV_ALIGN_BOTTOM_MID );
lv_textarea_set_placeholder_text(ui_settingsPincodeInput,"1234");
lv_textarea_set_one_line(ui_settingsPincodeInput,true);
lv_textarea_set_password_mode(ui_settingsPincodeInput, true);



ui_saveGeneralSettingsBtn = lv_btn_create(ui_Container6);
lv_obj_set_width( ui_saveGeneralSettingsBtn, 100);
lv_obj_set_height( ui_saveGeneralSettingsBtn, 50);
lv_obj_set_align( ui_saveGeneralSettingsBtn, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_add_flag( ui_saveGeneralSettingsBtn, LV_OBJ_FLAG_IGNORE_LAYOUT | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_saveGeneralSettingsBtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_saveGeneralSettingsBtn, lv_color_hex(0x1CD850), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_saveGeneralSettingsBtn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label23 = lv_label_create(ui_saveGeneralSettingsBtn);
lv_obj_set_width( ui_Label23, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label23, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label23, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label23,"Save");

ui_abortBtn3 = lv_btn_create(ui_Container6);
lv_obj_set_width( ui_abortBtn3, 100);
lv_obj_set_height( ui_abortBtn3, 50);
lv_obj_set_x( ui_abortBtn3, -110 );
lv_obj_set_y( ui_abortBtn3, 0 );
lv_obj_set_align( ui_abortBtn3, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_add_flag( ui_abortBtn3, LV_OBJ_FLAG_IGNORE_LAYOUT | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_abortBtn3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_abortBtn3, lv_color_hex(0xEA235F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_abortBtn3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label25 = lv_label_create(ui_abortBtn3);
lv_obj_set_width( ui_Label25, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label25, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label25, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label25,"Back");

ui_Container8 = lv_obj_create(ui_Container6);
lv_obj_remove_style_all(ui_Container8);
lv_obj_set_height( ui_Container8, 120);
lv_obj_set_width( ui_Container8, lv_pct(33));
lv_obj_set_align( ui_Container8, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_Container8, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Container8, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Container8, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Container8, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_settingsTimeout = lv_obj_create(ui_Container8);
lv_obj_set_height( ui_settingsTimeout, 110);
lv_obj_set_width( ui_settingsTimeout, lv_pct(100));
lv_obj_clear_flag( ui_settingsTimeout, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_settingsTimeoutLabel = lv_label_create(ui_settingsTimeout);
lv_obj_set_width( ui_settingsTimeoutLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_settingsTimeoutLabel, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_settingsTimeoutLabel,"Security timeout (sec)");

ui_settingsTimeoutInput = lv_textarea_create(ui_settingsTimeout);
lv_obj_set_width( ui_settingsTimeoutInput, lv_pct(100));
lv_obj_set_height( ui_settingsTimeoutInput, LV_SIZE_CONTENT);   /// 70
lv_obj_set_align( ui_settingsTimeoutInput, LV_ALIGN_BOTTOM_MID );
lv_textarea_set_placeholder_text(ui_settingsTimeoutInput,"30");
lv_textarea_set_one_line(ui_settingsTimeoutInput,true);



ui_Container9 = lv_obj_create(ui_Container6);
lv_obj_remove_style_all(ui_Container9);
lv_obj_set_height( ui_Container9, 120);
lv_obj_set_width( ui_Container9, lv_pct(33));
lv_obj_set_align( ui_Container9, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container9, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_Container9, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Container9, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Container9, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Container9, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_settingsConnectionTimeout = lv_obj_create(ui_Container9);
lv_obj_set_height( ui_settingsConnectionTimeout, 110);
lv_obj_set_width( ui_settingsConnectionTimeout, lv_pct(100));
lv_obj_clear_flag( ui_settingsConnectionTimeout, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_settingsConnectionTimeoutLabel = lv_label_create(ui_settingsConnectionTimeout);
lv_obj_set_width( ui_settingsConnectionTimeoutLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_settingsConnectionTimeoutLabel, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_settingsConnectionTimeoutLabel,"Connection timeout (sec)");

ui_settingsConnectionTimeoutInput = lv_textarea_create(ui_settingsConnectionTimeout);
lv_obj_set_width( ui_settingsConnectionTimeoutInput, lv_pct(100));
lv_obj_set_height( ui_settingsConnectionTimeoutInput, LV_SIZE_CONTENT);   /// 70
lv_obj_set_align( ui_settingsConnectionTimeoutInput, LV_ALIGN_BOTTOM_MID );
lv_textarea_set_placeholder_text(ui_settingsConnectionTimeoutInput,"3");
lv_textarea_set_one_line(ui_settingsConnectionTimeoutInput,true);



ui_Container10 = lv_obj_create(ui_Container6);
lv_obj_remove_style_all(ui_Container10);
lv_obj_set_height( ui_Container10, 120);
lv_obj_set_width( ui_Container10, lv_pct(33));
lv_obj_set_align( ui_Container10, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container10, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_Container10, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Container10, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Container10, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Container10, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_settingsMaxAttempts = lv_obj_create(ui_Container10);
lv_obj_set_height( ui_settingsMaxAttempts, 110);
lv_obj_set_width( ui_settingsMaxAttempts, lv_pct(100));
lv_obj_clear_flag( ui_settingsMaxAttempts, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_settingsMaxAttemptsLabel = lv_label_create(ui_settingsMaxAttempts);
lv_obj_set_width( ui_settingsMaxAttemptsLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_settingsMaxAttemptsLabel, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_settingsMaxAttemptsLabel,"Restart after failed connect");

ui_settingsMaxAttemptsInput = lv_textarea_create(ui_settingsMaxAttempts);
lv_obj_set_width( ui_settingsMaxAttemptsInput, lv_pct(100));
lv_obj_set_height( ui_settingsMaxAttemptsInput, LV_SIZE_CONTENT);   /// 70
lv_obj_set_align( ui_settingsMaxAttemptsInput, LV_ALIGN_BOTTOM_MID );
lv_textarea_set_placeholder_text(ui_settingsMaxAttemptsInput,"10");
lv_textarea_set_one_line(ui_settingsMaxAttemptsInput,true);



ui_Container11 = lv_obj_create(ui_Container6);
lv_obj_remove_style_all(ui_Container11);
lv_obj_set_height( ui_Container11, 120);
lv_obj_set_width( ui_Container11, lv_pct(33));
lv_obj_set_align( ui_Container11, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container11, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_Container11, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Container11, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Container11, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Container11, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_networkType = lv_obj_create(ui_Container11);
lv_obj_set_height( ui_networkType, 110);
lv_obj_set_width( ui_networkType, lv_pct(100));
lv_obj_clear_flag( ui_networkType, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_networkTypeLabel = lv_label_create(ui_networkType);
lv_obj_set_width( ui_networkTypeLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_networkTypeLabel, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_networkTypeLabel,"Use wifi");

ui_Label28 = lv_label_create(ui_networkType);
lv_obj_set_width( ui_Label28, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label28, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label28, -28 );
lv_obj_set_y( ui_Label28, 0 );
lv_obj_set_align( ui_Label28, LV_ALIGN_TOP_RIGHT );
lv_label_set_text(ui_Label28,"Use SIM");

ui_simNetworkType = lv_switch_create(ui_networkType);
lv_obj_set_width( ui_simNetworkType, 50);
lv_obj_set_height( ui_simNetworkType, 25);
lv_obj_set_x( ui_simNetworkType, 119 );
lv_obj_set_y( ui_simNetworkType, 40 );


ui_wiFiNetworkType = lv_switch_create(ui_networkType);
lv_obj_set_width( ui_wiFiNetworkType, 50);
lv_obj_set_height( ui_wiFiNetworkType, 25);
lv_obj_set_x( ui_wiFiNetworkType, -152 );
lv_obj_set_y( ui_wiFiNetworkType, 40 );
lv_obj_set_align( ui_wiFiNetworkType, LV_ALIGN_TOP_RIGHT );


ui_Container12 = lv_obj_create(ui_Container6);
lv_obj_remove_style_all(ui_Container12);
lv_obj_set_height( ui_Container12, 120);
lv_obj_set_width( ui_Container12, lv_pct(33));
lv_obj_set_align( ui_Container12, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container12, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_Container12, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Container12, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Container12, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Container12, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_phone = lv_obj_create(ui_Container12);
lv_obj_set_height( ui_phone, 110);
lv_obj_set_width( ui_phone, lv_pct(100));
lv_obj_clear_flag( ui_phone, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_phoneLabel = lv_label_create(ui_phone);
lv_obj_set_width( ui_phoneLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_phoneLabel, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_phoneLabel,"Phone");

ui_settingsPhoneInput = lv_textarea_create(ui_phone);
lv_obj_set_width( ui_settingsPhoneInput, lv_pct(100));
lv_obj_set_height( ui_settingsPhoneInput, LV_SIZE_CONTENT);   /// 70
lv_obj_set_align( ui_settingsPhoneInput, LV_ALIGN_BOTTOM_MID );
lv_textarea_set_placeholder_text(ui_settingsPhoneInput,"Phone");
lv_textarea_set_one_line(ui_settingsPhoneInput,true);



ui_Keyboard4 = lv_keyboard_create(ui_Container6);
lv_obj_set_width( ui_Keyboard4, lv_pct(100));
lv_obj_set_height( ui_Keyboard4, lv_pct(50));
lv_obj_set_align( ui_Keyboard4, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( ui_Keyboard4, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_IGNORE_LAYOUT );   /// Flags

lv_obj_add_event_cb(ui_settingsPincodeInput, ui_event_settingsPincodeInput, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Label23, ui_event_Label23, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_saveGeneralSettingsBtn, ui_event_saveGeneralSettingsBtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_abortBtn3, ui_event_abortBtn3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_settingsTimeoutInput, ui_event_settingsTimeoutInput, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_settingsConnectionTimeoutInput, ui_event_settingsConnectionTimeoutInput, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_settingsMaxAttemptsInput, ui_event_settingsMaxAttemptsInput, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_simNetworkType, ui_event_simNetworkType, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_wiFiNetworkType, ui_event_wiFiNetworkType, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_settingsPhoneInput, ui_event_settingsPhoneInput, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Keyboard4, ui_event_Keyboard4, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_generalSettingsScreen, ui_event_generalSettingsScreen, LV_EVENT_ALL, NULL);

}
