// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_generalSettingsScreen_screen_init(void)
{
ui_generalSettingsScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_generalSettingsScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_TabView7 = lv_tabview_create(ui_generalSettingsScreen, LV_DIR_TOP, 50);
lv_obj_set_width( ui_TabView7, 800);
lv_obj_set_height( ui_TabView7, 480);
lv_obj_set_align( ui_TabView7, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_TabView7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_TabView7), lv_color_hex(0x2095F6),  LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_TabView7), 255,  LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label21 = lv_label_create(ui_generalSettingsScreen);
lv_obj_set_width( ui_Label21, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label21, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_Label21,"General settings");
lv_obj_set_style_text_font(ui_Label21, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Label21, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Label21, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Label21, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Label21, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container6 = lv_obj_create(ui_generalSettingsScreen);
lv_obj_remove_style_all(ui_Container6);
lv_obj_set_width( ui_Container6, 800);
lv_obj_set_height( ui_Container6, 480);
lv_obj_set_align( ui_Container6, LV_ALIGN_CENTER );
lv_obj_set_scrollbar_mode(ui_Container6, LV_SCROLLBAR_MODE_ON);
lv_obj_set_scroll_dir(ui_Container6, LV_DIR_BOTTOM);
lv_obj_set_style_pad_left(ui_Container6, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Container6, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Container6, 70, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Container6, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_settingsPincode = lv_obj_create(ui_Container6);
lv_obj_set_height( ui_settingsPincode, 120);
lv_obj_set_width( ui_settingsPincode, lv_pct(32));
lv_obj_clear_flag( ui_settingsPincode, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_pinlabel = lv_label_create(ui_settingsPincode);
lv_obj_set_width( ui_pinlabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_pinlabel, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_pinlabel,"PIN code");

ui_settingsPincodeInput = lv_textarea_create(ui_settingsPincode);
lv_obj_set_width( ui_settingsPincodeInput, lv_pct(100));
lv_obj_set_height( ui_settingsPincodeInput, LV_SIZE_CONTENT);   /// 70
lv_obj_set_align( ui_settingsPincodeInput, LV_ALIGN_BOTTOM_MID );
lv_textarea_set_placeholder_text(ui_settingsPincodeInput,"PIN");
lv_textarea_set_one_line(ui_settingsPincodeInput,true);
lv_textarea_set_password_mode(ui_settingsPincodeInput, true);



ui_saveGeneralSettingsBtn = lv_btn_create(ui_Container6);
lv_obj_set_width( ui_saveGeneralSettingsBtn, 100);
lv_obj_set_height( ui_saveGeneralSettingsBtn, 50);
lv_obj_set_align( ui_saveGeneralSettingsBtn, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_add_flag( ui_saveGeneralSettingsBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_saveGeneralSettingsBtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_saveGeneralSettingsBtn, lv_color_hex(0x1CD850), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_saveGeneralSettingsBtn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label23 = lv_label_create(ui_saveGeneralSettingsBtn);
lv_obj_set_width( ui_Label23, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label23, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label23, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label23,"Save");

ui_abortBtn3 = lv_btn_create(ui_Container6);
lv_obj_set_width( ui_abortBtn3, 100);
lv_obj_set_height( ui_abortBtn3, 50);
lv_obj_set_x( ui_abortBtn3, -110 );
lv_obj_set_y( ui_abortBtn3, 0 );
lv_obj_set_align( ui_abortBtn3, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_add_flag( ui_abortBtn3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_abortBtn3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_abortBtn3, lv_color_hex(0xEA235F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_abortBtn3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label25 = lv_label_create(ui_abortBtn3);
lv_obj_set_width( ui_Label25, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label25, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label25, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label25,"Back");

ui_Keyboard4 = lv_keyboard_create(ui_generalSettingsScreen);
lv_obj_set_width( ui_Keyboard4, lv_pct(100));
lv_obj_set_height( ui_Keyboard4, lv_pct(50));
lv_obj_set_align( ui_Keyboard4, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( ui_Keyboard4, LV_OBJ_FLAG_HIDDEN );   /// Flags

lv_obj_add_event_cb(ui_settingsPincodeInput, ui_event_settingsPincodeInput, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Label23, ui_event_Label23, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_saveGeneralSettingsBtn, ui_event_saveGeneralSettingsBtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_abortBtn3, ui_event_abortBtn3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Keyboard4, ui_event_Keyboard4, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_generalSettingsScreen, ui_event_generalSettingsScreen, LV_EVENT_ALL, NULL);

}
