// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_home_screen_init(void)
{
ui_home = lv_obj_create(NULL);
lv_obj_clear_flag( ui_home, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_text_font(ui_home, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TabView1 = lv_tabview_create(ui_home, LV_DIR_TOP, 50);
lv_obj_set_width( ui_TabView1, 800);
lv_obj_set_height( ui_TabView1, 480);
lv_obj_set_align( ui_TabView1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_TabView1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_TabView1), lv_color_hex(0x2095F6),  LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_TabView1), 255,  LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label1 = lv_label_create(ui_home);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_Label1,"IoT Security");
lv_obj_set_style_pad_left(ui_Label1, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Label1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Label1, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Label1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container2 = lv_obj_create(ui_home);
lv_obj_remove_style_all(ui_Container2);
lv_obj_set_width( ui_Container2, 800);
lv_obj_set_height( ui_Container2, 480);
lv_obj_set_align( ui_Container2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_Container2, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Container2, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Container2, 70, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Container2, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_mqttHome = lv_obj_create(ui_Container2);
lv_obj_set_height( ui_mqttHome, 309);
lv_obj_set_width( ui_mqttHome, lv_pct(50));
lv_obj_clear_flag( ui_mqttHome, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label2 = lv_label_create(ui_mqttHome);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_Label2,"MQTT Configruration");

ui_mqttSettingsBtn = lv_btn_create(ui_mqttHome);
lv_obj_set_width( ui_mqttSettingsBtn, 100);
lv_obj_set_height( ui_mqttSettingsBtn, 50);
lv_obj_set_align( ui_mqttSettingsBtn, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_add_flag( ui_mqttSettingsBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_mqttSettingsBtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label3 = lv_label_create(ui_mqttSettingsBtn);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"Edit");

ui_Spinner1 = lv_spinner_create(ui_mqttHome,1000,90);
lv_obj_set_width( ui_Spinner1, 40);
lv_obj_set_height( ui_Spinner1, 40);
lv_obj_set_align( ui_Spinner1, LV_ALIGN_TOP_RIGHT );
lv_obj_clear_flag( ui_Spinner1, LV_OBJ_FLAG_CLICKABLE );    /// Flags

lv_obj_set_style_arc_color(ui_Spinner1, lv_color_hex(0xFF406A), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Spinner1, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_Container3 = lv_obj_create(ui_mqttHome);
lv_obj_remove_style_all(ui_Container3);
lv_obj_set_width( ui_Container3, lv_pct(100));
lv_obj_set_height( ui_Container3, lv_pct(50));
lv_obj_set_align( ui_Container3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_mqttAddrLabel = lv_label_create(ui_Container3);
lv_obj_set_width( ui_mqttAddrLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_mqttAddrLabel, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_mqttAddrLabel,"");

ui_mqttCredentialsLabel = lv_label_create(ui_Container3);
lv_obj_set_width( ui_mqttCredentialsLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_mqttCredentialsLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_mqttCredentialsLabel, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_mqttCredentialsLabel,"");

ui_wifiHome = lv_obj_create(ui_Container2);
lv_obj_set_height( ui_wifiHome, 150);
lv_obj_set_width( ui_wifiHome, lv_pct(48));
lv_obj_set_align( ui_wifiHome, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( ui_wifiHome, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_wifiHome, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label9 = lv_label_create(ui_wifiHome);
lv_obj_set_width( ui_Label9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label9, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_Label9,"WIFI Settings");

ui_wifiSettingsBtn = lv_btn_create(ui_wifiHome);
lv_obj_set_width( ui_wifiSettingsBtn, 100);
lv_obj_set_height( ui_wifiSettingsBtn, 50);
lv_obj_set_align( ui_wifiSettingsBtn, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_add_flag( ui_wifiSettingsBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_wifiSettingsBtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label12 = lv_label_create(ui_wifiSettingsBtn);
lv_obj_set_width( ui_Label12, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label12, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label12, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label12,"Edit");

ui_wifiSsidLabel = lv_label_create(ui_wifiHome);
lv_obj_set_width( ui_wifiSsidLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wifiSsidLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_wifiSsidLabel, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_wifiSsidLabel,"");

ui_connectionStatusWifiOff = lv_img_create(ui_wifiHome);
lv_img_set_src(ui_connectionStatusWifiOff, &ui_img_1515518950);
lv_obj_set_width( ui_connectionStatusWifiOff, LV_SIZE_CONTENT);  /// 50
lv_obj_set_height( ui_connectionStatusWifiOff, LV_SIZE_CONTENT);   /// 50
lv_obj_set_x( ui_connectionStatusWifiOff, 0 );
lv_obj_set_y( ui_connectionStatusWifiOff, -15 );
lv_obj_set_align( ui_connectionStatusWifiOff, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_connectionStatusWifiOff, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_connectionStatusWifiOff, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_connectionStatusWifiOn = lv_img_create(ui_wifiHome);
lv_img_set_src(ui_connectionStatusWifiOn, &ui_img_548092219);
lv_obj_set_width( ui_connectionStatusWifiOn, LV_SIZE_CONTENT);  /// 50
lv_obj_set_height( ui_connectionStatusWifiOn, LV_SIZE_CONTENT);   /// 50
lv_obj_set_x( ui_connectionStatusWifiOn, 0 );
lv_obj_set_y( ui_connectionStatusWifiOn, -15 );
lv_obj_set_align( ui_connectionStatusWifiOn, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_connectionStatusWifiOn, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_connectionStatusWifiOn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_sensorsHome = lv_obj_create(ui_Container2);
lv_obj_set_height( ui_sensorsHome, 150);
lv_obj_set_width( ui_sensorsHome, lv_pct(48));
lv_obj_set_x( ui_sensorsHome, 0 );
lv_obj_set_y( ui_sensorsHome, -90 );
lv_obj_set_align( ui_sensorsHome, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_clear_flag( ui_sensorsHome, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_SensorsLabel = lv_label_create(ui_sensorsHome);
lv_obj_set_width( ui_SensorsLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SensorsLabel, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_SensorsLabel,"Sensors");

ui_addSensorBtn = lv_btn_create(ui_sensorsHome);
lv_obj_set_width( ui_addSensorBtn, 100);
lv_obj_set_height( ui_addSensorBtn, 50);
lv_obj_set_align( ui_addSensorBtn, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_add_flag( ui_addSensorBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_addSensorBtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_addSensorBtn, lv_color_hex(0xEA235F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_addSensorBtn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label13 = lv_label_create(ui_addSensorBtn);
lv_obj_set_width( ui_Label13, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label13, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label13, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label13,"Add");

ui_sensorsQty = lv_label_create(ui_sensorsHome);
lv_obj_set_width( ui_sensorsQty, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_sensorsQty, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_sensorsQty, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_sensorsQty,"");

ui_controlsHome = lv_obj_create(ui_Container2);
lv_obj_set_height( ui_controlsHome, 75);
lv_obj_set_width( ui_controlsHome, lv_pct(100));
lv_obj_set_align( ui_controlsHome, LV_ALIGN_BOTTOM_LEFT );
lv_obj_clear_flag( ui_controlsHome, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label33 = lv_label_create(ui_controlsHome);
lv_obj_set_width( ui_Label33, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label33, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_Label33,"Controls");

ui_AddControlBtn = lv_btn_create(ui_controlsHome);
lv_obj_set_width( ui_AddControlBtn, 100);
lv_obj_set_height( ui_AddControlBtn, 50);
lv_obj_set_align( ui_AddControlBtn, LV_ALIGN_RIGHT_MID );
lv_obj_add_flag( ui_AddControlBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_AddControlBtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_AddControlBtn, lv_color_hex(0xEE205A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_AddControlBtn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label34 = lv_label_create(ui_AddControlBtn);
lv_obj_set_width( ui_Label34, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label34, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label34, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label34,"Add");

ui_simHome = lv_obj_create(ui_Container2);
lv_obj_set_height( ui_simHome, 150);
lv_obj_set_width( ui_simHome, lv_pct(48));
lv_obj_set_align( ui_simHome, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( ui_simHome, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_simHome, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label29 = lv_label_create(ui_simHome);
lv_obj_set_width( ui_Label29, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label29, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_Label29,"Sim status");

ui_connectionStatusSimOff = lv_img_create(ui_simHome);
lv_img_set_src(ui_connectionStatusSimOff, &ui_img_1515518950);
lv_obj_set_width( ui_connectionStatusSimOff, LV_SIZE_CONTENT);  /// 50
lv_obj_set_height( ui_connectionStatusSimOff, LV_SIZE_CONTENT);   /// 50
lv_obj_set_x( ui_connectionStatusSimOff, 0 );
lv_obj_set_y( ui_connectionStatusSimOff, -15 );
lv_obj_set_align( ui_connectionStatusSimOff, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_connectionStatusSimOff, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_connectionStatusSimOff, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_connectionStatusSimOn = lv_img_create(ui_simHome);
lv_img_set_src(ui_connectionStatusSimOn, &ui_img_548092219);
lv_obj_set_width( ui_connectionStatusSimOn, LV_SIZE_CONTENT);  /// 50
lv_obj_set_height( ui_connectionStatusSimOn, LV_SIZE_CONTENT);   /// 50
lv_obj_set_x( ui_connectionStatusSimOn, 0 );
lv_obj_set_y( ui_connectionStatusSimOn, -15 );
lv_obj_set_align( ui_connectionStatusSimOn, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_connectionStatusSimOn, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_connectionStatusSimOn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_goToGeneralSettingsBtn = lv_imgbtn_create(ui_home);
lv_imgbtn_set_src(ui_goToGeneralSettingsBtn, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_setting_png, NULL);
lv_obj_set_height( ui_goToGeneralSettingsBtn, 32);
lv_obj_set_width( ui_goToGeneralSettingsBtn, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_goToGeneralSettingsBtn, -20 );
lv_obj_set_y( ui_goToGeneralSettingsBtn, 7 );
lv_obj_set_align( ui_goToGeneralSettingsBtn, LV_ALIGN_TOP_RIGHT );

ui_lockBtn = lv_imgbtn_create(ui_home);
lv_imgbtn_set_src(ui_lockBtn, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_padlock_png, NULL);
lv_obj_set_height( ui_lockBtn, 32);
lv_obj_set_width( ui_lockBtn, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_lockBtn, 150 );
lv_obj_set_y( ui_lockBtn, 5 );

lv_obj_add_event_cb(ui_mqttSettingsBtn, ui_event_mqttSettingsBtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_wifiSettingsBtn, ui_event_wifiSettingsBtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_addSensorBtn, ui_event_addSensorBtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_AddControlBtn, ui_event_AddControlBtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_goToGeneralSettingsBtn, ui_event_goToGeneralSettingsBtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_lockBtn, ui_event_lockBtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_home, ui_event_home, LV_EVENT_ALL, NULL);

}
