// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_wifiConfigScreen_screen_init(void)
{
ui_wifiConfigScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_wifiConfigScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_TabView3 = lv_tabview_create(ui_wifiConfigScreen, LV_DIR_TOP, 50);
lv_obj_set_width( ui_TabView3, 800);
lv_obj_set_height( ui_TabView3, 480);
lv_obj_set_align( ui_TabView3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_TabView3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_TabView3), lv_color_hex(0x2095F6),  LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_TabView3), 255,  LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label8 = lv_label_create(ui_wifiConfigScreen);
lv_obj_set_width( ui_Label8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label8, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_Label8,"WIFI Settings");
lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Label8, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Label8, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Label8, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Label8, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container4 = lv_obj_create(ui_wifiConfigScreen);
lv_obj_remove_style_all(ui_Container4);
lv_obj_set_width( ui_Container4, 800);
lv_obj_set_height( ui_Container4, 480);
lv_obj_set_align( ui_Container4, LV_ALIGN_CENTER );
lv_obj_set_scrollbar_mode(ui_Container4, LV_SCROLLBAR_MODE_ON);
lv_obj_set_scroll_dir(ui_Container4, LV_DIR_BOTTOM);
lv_obj_set_style_pad_left(ui_Container4, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Container4, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Container4, 70, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Container4, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ssid = lv_obj_create(ui_Container4);
lv_obj_set_height( ui_ssid, 120);
lv_obj_set_width( ui_ssid, lv_pct(32));
lv_obj_clear_flag( ui_ssid, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_wifiSsidInputLabel = lv_label_create(ui_ssid);
lv_obj_set_width( ui_wifiSsidInputLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wifiSsidInputLabel, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_wifiSsidInputLabel,"WIFI ssid");

ui_wifiSsid = lv_textarea_create(ui_ssid);
lv_obj_set_width( ui_wifiSsid, lv_pct(100));
lv_obj_set_height( ui_wifiSsid, LV_SIZE_CONTENT);   /// 70
lv_obj_set_align( ui_wifiSsid, LV_ALIGN_BOTTOM_MID );
lv_textarea_set_placeholder_text(ui_wifiSsid,"ssid");
lv_textarea_set_one_line(ui_wifiSsid,true);



ui_Port1 = lv_obj_create(ui_Container4);
lv_obj_set_height( ui_Port1, 120);
lv_obj_set_width( ui_Port1, lv_pct(32));
lv_obj_set_align( ui_Port1, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_Port1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_wifiPassInputLabel = lv_label_create(ui_Port1);
lv_obj_set_width( ui_wifiPassInputLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wifiPassInputLabel, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_wifiPassInputLabel,"WIFI Password");

ui_wifiPassword = lv_textarea_create(ui_Port1);
lv_obj_set_width( ui_wifiPassword, lv_pct(100));
lv_obj_set_height( ui_wifiPassword, LV_SIZE_CONTENT);   /// 70
lv_obj_set_align( ui_wifiPassword, LV_ALIGN_BOTTOM_MID );
lv_textarea_set_placeholder_text(ui_wifiPassword,"password");
lv_textarea_set_one_line(ui_wifiPassword,true);
lv_textarea_set_password_mode(ui_wifiPassword, true);



ui_saveWifiBtn = lv_btn_create(ui_Container4);
lv_obj_set_width( ui_saveWifiBtn, 100);
lv_obj_set_height( ui_saveWifiBtn, 50);
lv_obj_set_align( ui_saveWifiBtn, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_add_flag( ui_saveWifiBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_saveWifiBtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_saveWifiBtn, lv_color_hex(0x1CD850), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_saveWifiBtn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label10 = lv_label_create(ui_saveWifiBtn);
lv_obj_set_width( ui_Label10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label10, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label10,"Save");

ui_abortBtn1 = lv_btn_create(ui_Container4);
lv_obj_set_width( ui_abortBtn1, 100);
lv_obj_set_height( ui_abortBtn1, 50);
lv_obj_set_x( ui_abortBtn1, -110 );
lv_obj_set_y( ui_abortBtn1, 0 );
lv_obj_set_align( ui_abortBtn1, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_add_flag( ui_abortBtn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_abortBtn1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_abortBtn1, lv_color_hex(0xEA235F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_abortBtn1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label11 = lv_label_create(ui_abortBtn1);
lv_obj_set_width( ui_Label11, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label11, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label11, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label11,"Back");

ui_Keyboard1 = lv_keyboard_create(ui_wifiConfigScreen);
lv_obj_set_width( ui_Keyboard1, lv_pct(100));
lv_obj_set_height( ui_Keyboard1, lv_pct(50));
lv_obj_set_align( ui_Keyboard1, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( ui_Keyboard1, LV_OBJ_FLAG_HIDDEN );   /// Flags

lv_obj_add_event_cb(ui_wifiSsid, ui_event_wifiSsid, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_wifiPassword, ui_event_wifiPassword, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Label10, ui_event_Label10, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_saveWifiBtn, ui_event_saveWifiBtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_abortBtn1, ui_event_abortBtn1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Keyboard1, ui_event_Keyboard1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_wifiConfigScreen, ui_event_wifiConfigScreen, LV_EVENT_ALL, NULL);

}
