// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_COMP_CONTROLITEM_H
#define _UI_COMP_CONTROLITEM_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT ControlItem
#define UI_COMP_CONTROLITEM_CONTROLITEM 0
#define UI_COMP_CONTROLITEM_CONTROLPANEL 1
#define UI_COMP_CONTROLITEM_CONTROLPANEL_GUARDPANEL 2
#define UI_COMP_CONTROLITEM_CONTROLPANEL_GUARDPANEL_LABEL28 3
#define UI_COMP_CONTROLITEM_CONTROLPANEL_GUARDPANEL_GUARDOK 4
#define UI_COMP_CONTROLITEM_CONTROLPANEL_DISARMPANEL 5
#define UI_COMP_CONTROLITEM_CONTROLPANEL_DISARMPANEL_LABEL29 6
#define UI_COMP_CONTROLITEM_CONTROLPANEL_DISARMPANEL_DISARMOK 7
#define UI_COMP_CONTROLITEM_CONTROLPANEL_MUTEPANEL 8
#define UI_COMP_CONTROLITEM_CONTROLPANEL_MUTEPANEL_LABEL30 9
#define UI_COMP_CONTROLITEM_CONTROLPANEL_MUTEPANEL_MUTEOK 10
#define UI_COMP_CONTROLITEM_CONTROLPANEL_ALARMPANEL 11
#define UI_COMP_CONTROLITEM_CONTROLPANEL_ALARMPANEL_LABEL31 12
#define UI_COMP_CONTROLITEM_CONTROLPANEL_ALARMPANEL_ALARMOK 13
#define UI_COMP_CONTROLITEM_CONTROLPANEL_CONTROLID 14
#define UI_COMP_CONTROLITEM_CONTROLPANEL_DELETECONTROLBTN 15
#define UI_COMP_CONTROLITEM_CONTROLPANEL_DELETECONTROLBTN_LABEL32 16
#define _UI_COMP_CONTROLITEM_NUM 17
lv_obj_t *ui_ControlItem_create(lv_obj_t *comp_parent);
void ui_event_comp_ControlItem_GuardPanel( lv_event_t * e);
void ui_event_comp_ControlItem_DisarmPanel( lv_event_t * e);
void ui_event_comp_ControlItem_MutePanel( lv_event_t * e);
void ui_event_comp_ControlItem_AlarmPanel( lv_event_t * e);
void ui_event_comp_ControlItem_DeleteControlBtn( lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
