// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_COMP_SENSORITEM_H
#define _UI_COMP_SENSORITEM_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT SensorItem
#define UI_COMP_SENSORITEM_SENSORITEM 0
#define UI_COMP_SENSORITEM_SENSORITEMPANEL 1
#define UI_COMP_SENSORITEM_SENSORITEMPANEL_SENSORID 2
#define UI_COMP_SENSORITEM_SENSORITEMPANEL_DELETESENSORBTN 3
#define UI_COMP_SENSORITEM_SENSORITEMPANEL_DELETESENSORBTN_LABEL20 4
#define UI_COMP_SENSORITEM_SENSORITEMPANEL_EDITSENSORBTN 5
#define UI_COMP_SENSORITEM_SENSORITEMPANEL_EDITSENSORBTN_LABEL21 6
#define UI_COMP_SENSORITEM_SENSORITEMPANEL_LABEL15 7
#define _UI_COMP_SENSORITEM_NUM 8

lv_obj_t *ui_SensorItem_create(lv_obj_t *comp_parent);

void ui_event_comp_SensorItem_deleteSensorBtn(lv_event_t *e);

void ui_event_comp_SensorItem_editSensorBtn(lv_event_t *e);

void goToEditSensor(lv_event_t *e);

void deleteSensor(lv_event_t *e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
