// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"


void ui_event_comp_SensorItem_deleteSensorBtn( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
lv_obj_t **comp_SensorItem = lv_event_get_user_data(e);
if ( event_code == LV_EVENT_CLICKED) {
      deleteSensor( e );
}
}
void ui_event_comp_SensorItem_editSensorBtn( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
lv_obj_t **comp_SensorItem = lv_event_get_user_data(e);
if ( event_code == LV_EVENT_CLICKED) {
      goToEditSensor( e );
}
}

// COMPONENT SensorItem

lv_obj_t *ui_SensorItem_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_SensorItem;
cui_SensorItem = lv_obj_create(comp_parent);
lv_obj_remove_style_all(cui_SensorItem);
lv_obj_set_height( cui_SensorItem, 120);
lv_obj_set_width( cui_SensorItem, lv_pct(33));
lv_obj_set_align( cui_SensorItem, LV_ALIGN_CENTER );
lv_obj_clear_flag( cui_SensorItem, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(cui_SensorItem, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_SensorItem, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_SensorItem, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_SensorItem, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_SensorItemPanel;
cui_SensorItemPanel = lv_obj_create(cui_SensorItem);
lv_obj_set_width( cui_SensorItemPanel, lv_pct(100));
lv_obj_set_height( cui_SensorItemPanel, lv_pct(100));
lv_obj_set_align( cui_SensorItemPanel, LV_ALIGN_CENTER );
lv_obj_clear_flag( cui_SensorItemPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_t *cui_sensorId;
cui_sensorId = lv_label_create(cui_SensorItemPanel);
lv_obj_set_width( cui_sensorId, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_sensorId, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(cui_sensorId,"21414");

lv_obj_t *cui_deleteSensorBtn;
cui_deleteSensorBtn = lv_btn_create(cui_SensorItemPanel);
lv_obj_set_width( cui_deleteSensorBtn, 80);
lv_obj_set_height( cui_deleteSensorBtn, 30);
lv_obj_set_align( cui_deleteSensorBtn, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_add_flag( cui_deleteSensorBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( cui_deleteSensorBtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(cui_deleteSensorBtn, lv_color_hex(0xC73D3D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_deleteSensorBtn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_Label20;
cui_Label20 = lv_label_create(cui_deleteSensorBtn);
lv_obj_set_width( cui_Label20, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_Label20, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_Label20, LV_ALIGN_CENTER );
lv_label_set_text(cui_Label20,"Delete");

lv_obj_t *cui_editSensorBtn;
cui_editSensorBtn = lv_btn_create(cui_SensorItemPanel);
lv_obj_set_width( cui_editSensorBtn, 80);
lv_obj_set_height( cui_editSensorBtn, 30);
lv_obj_set_align( cui_editSensorBtn, LV_ALIGN_BOTTOM_LEFT );
lv_obj_add_flag( cui_editSensorBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( cui_editSensorBtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(cui_editSensorBtn, lv_color_hex(0x7E2FB0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_editSensorBtn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_Label21;
cui_Label21 = lv_label_create(cui_editSensorBtn);
lv_obj_set_width( cui_Label21, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_Label21, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_Label21, LV_ALIGN_CENTER );
lv_label_set_text(cui_Label21,"Edit");

lv_obj_t *cui_Label15;
cui_Label15 = lv_label_create(cui_SensorItemPanel);
lv_obj_set_width( cui_Label15, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_Label15, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_Label15, LV_ALIGN_TOP_RIGHT );
lv_label_set_text(cui_Label15,"New!");
lv_obj_add_flag( cui_Label15, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_set_style_text_color(cui_Label15, lv_color_hex(0x1AB436), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(cui_Label15, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_SENSORITEM_NUM);
children[UI_COMP_SENSORITEM_SENSORITEM] = cui_SensorItem;
children[UI_COMP_SENSORITEM_SENSORITEMPANEL] = cui_SensorItemPanel;
children[UI_COMP_SENSORITEM_SENSORITEMPANEL_SENSORID] = cui_sensorId;
children[UI_COMP_SENSORITEM_SENSORITEMPANEL_DELETESENSORBTN] = cui_deleteSensorBtn;
children[UI_COMP_SENSORITEM_SENSORITEMPANEL_DELETESENSORBTN_LABEL20] = cui_Label20;
children[UI_COMP_SENSORITEM_SENSORITEMPANEL_EDITSENSORBTN] = cui_editSensorBtn;
children[UI_COMP_SENSORITEM_SENSORITEMPANEL_EDITSENSORBTN_LABEL21] = cui_Label21;
children[UI_COMP_SENSORITEM_SENSORITEMPANEL_LABEL15] = cui_Label15;
lv_obj_add_event_cb(cui_SensorItem, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_SensorItem, del_component_child_event_cb, LV_EVENT_DELETE, children);
lv_obj_add_event_cb(cui_deleteSensorBtn, ui_event_comp_SensorItem_deleteSensorBtn, LV_EVENT_ALL, children);
lv_obj_add_event_cb(cui_editSensorBtn, ui_event_comp_SensorItem_editSensorBtn, LV_EVENT_ALL, children);
ui_comp_SensorItem_create_hook(cui_SensorItem);
return cui_SensorItem; 
}

