// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"


void ui_event_comp_ControlItem_GuardPanel( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
lv_obj_t **comp_ControlItem = lv_event_get_user_data(e);
if ( event_code == LV_EVENT_LONG_PRESSED) {
      addControlAction( e );
}
}
void ui_event_comp_ControlItem_DisarmPanel( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
lv_obj_t **comp_ControlItem = lv_event_get_user_data(e);
if ( event_code == LV_EVENT_LONG_PRESSED) {
      addControlAction( e );
}
}
void ui_event_comp_ControlItem_MutePanel( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
lv_obj_t **comp_ControlItem = lv_event_get_user_data(e);
if ( event_code == LV_EVENT_LONG_PRESSED) {
      addControlAction( e );
}
}
void ui_event_comp_ControlItem_AlarmPanel( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
lv_obj_t **comp_ControlItem = lv_event_get_user_data(e);
if ( event_code == LV_EVENT_LONG_PRESSED) {
      addControlAction( e );
}
}
void ui_event_comp_ControlItem_DeleteControlBtn( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
lv_obj_t **comp_ControlItem = lv_event_get_user_data(e);
if ( event_code == LV_EVENT_CLICKED) {
      deleteControl( e );
}
}

// COMPONENT ControlItem

lv_obj_t *ui_ControlItem_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_ControlItem;
cui_ControlItem = lv_obj_create(comp_parent);
lv_obj_remove_style_all(cui_ControlItem);
lv_obj_set_height( cui_ControlItem, 190);
lv_obj_set_width( cui_ControlItem, lv_pct(100));
lv_obj_set_align( cui_ControlItem, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(cui_ControlItem,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(cui_ControlItem, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( cui_ControlItem, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_t *cui_ControlPanel;
cui_ControlPanel = lv_obj_create(cui_ControlItem);
lv_obj_set_height( cui_ControlPanel, 180);
lv_obj_set_width( cui_ControlPanel, lv_pct(100));
lv_obj_set_align( cui_ControlPanel, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(cui_ControlPanel,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(cui_ControlPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( cui_ControlPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(cui_ControlPanel, lv_color_hex(0x266E87), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_ControlPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(cui_ControlPanel, lv_color_hex(0x2F1616), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(cui_ControlPanel, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_ControlPanel, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_ControlPanel, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_ControlPanel, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_ControlPanel, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_GuardPanel;
cui_GuardPanel = lv_obj_create(cui_ControlPanel);
lv_obj_set_width( cui_GuardPanel, 180);
lv_obj_set_height( cui_GuardPanel, lv_pct(70));
lv_obj_set_align( cui_GuardPanel, LV_ALIGN_CENTER );
lv_obj_clear_flag( cui_GuardPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_t *cui_Label28;
cui_Label28 = lv_label_create(cui_GuardPanel);
lv_obj_set_width( cui_Label28, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_Label28, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(cui_Label28,"Guard");

lv_obj_t *cui_GuardOk;
cui_GuardOk = lv_img_create(cui_GuardPanel);
lv_obj_set_width( cui_GuardOk, LV_SIZE_CONTENT);  /// 32
lv_obj_set_height( cui_GuardOk, LV_SIZE_CONTENT);   /// 32
lv_obj_set_align( cui_GuardOk, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( cui_GuardOk, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( cui_GuardOk, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_t *cui_DisarmPanel;
cui_DisarmPanel = lv_obj_create(cui_ControlPanel);
lv_obj_set_width( cui_DisarmPanel, 180);
lv_obj_set_height( cui_DisarmPanel, lv_pct(70));
lv_obj_set_align( cui_DisarmPanel, LV_ALIGN_CENTER );
lv_obj_clear_flag( cui_DisarmPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_t *cui_Label29;
cui_Label29 = lv_label_create(cui_DisarmPanel);
lv_obj_set_width( cui_Label29, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_Label29, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(cui_Label29,"Disarm");

lv_obj_t *cui_DisarmOk;
cui_DisarmOk = lv_img_create(cui_DisarmPanel);
lv_obj_set_width( cui_DisarmOk, LV_SIZE_CONTENT);  /// 32
lv_obj_set_height( cui_DisarmOk, LV_SIZE_CONTENT);   /// 32
lv_obj_set_align( cui_DisarmOk, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( cui_DisarmOk, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( cui_DisarmOk, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_t *cui_MutePanel;
cui_MutePanel = lv_obj_create(cui_ControlPanel);
lv_obj_set_width( cui_MutePanel, 180);
lv_obj_set_height( cui_MutePanel, lv_pct(70));
lv_obj_set_align( cui_MutePanel, LV_ALIGN_CENTER );
lv_obj_clear_flag( cui_MutePanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_t *cui_Label30;
cui_Label30 = lv_label_create(cui_MutePanel);
lv_obj_set_width( cui_Label30, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_Label30, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(cui_Label30,"Mute");

lv_obj_t *cui_MuteOk;
cui_MuteOk = lv_img_create(cui_MutePanel);
lv_obj_set_width( cui_MuteOk, LV_SIZE_CONTENT);  /// 32
lv_obj_set_height( cui_MuteOk, LV_SIZE_CONTENT);   /// 32
lv_obj_set_align( cui_MuteOk, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( cui_MuteOk, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( cui_MuteOk, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_t *cui_AlarmPanel;
cui_AlarmPanel = lv_obj_create(cui_ControlPanel);
lv_obj_set_width( cui_AlarmPanel, 180);
lv_obj_set_height( cui_AlarmPanel, lv_pct(70));
lv_obj_set_align( cui_AlarmPanel, LV_ALIGN_CENTER );
lv_obj_clear_flag( cui_AlarmPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_t *cui_Label31;
cui_Label31 = lv_label_create(cui_AlarmPanel);
lv_obj_set_width( cui_Label31, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_Label31, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(cui_Label31,"Alarm");

lv_obj_t *cui_AlarmOk;
cui_AlarmOk = lv_img_create(cui_AlarmPanel);
lv_obj_set_width( cui_AlarmOk, LV_SIZE_CONTENT);  /// 32
lv_obj_set_height( cui_AlarmOk, LV_SIZE_CONTENT);   /// 32
lv_obj_set_align( cui_AlarmOk, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( cui_AlarmOk, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( cui_AlarmOk, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_t *cui_controlId;
cui_controlId = lv_label_create(cui_ControlPanel);
lv_obj_set_width( cui_controlId, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_controlId, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_controlId, LV_ALIGN_BOTTOM_LEFT );
lv_label_set_text(cui_controlId,"");
lv_obj_add_flag( cui_controlId, LV_OBJ_FLAG_IGNORE_LAYOUT );   /// Flags

lv_obj_t *cui_DeleteControlBtn;
cui_DeleteControlBtn = lv_btn_create(cui_ControlPanel);
lv_obj_set_width( cui_DeleteControlBtn, 80);
lv_obj_set_height( cui_DeleteControlBtn, 30);
lv_obj_set_x( cui_DeleteControlBtn, -10 );
lv_obj_set_y( cui_DeleteControlBtn, 0 );
lv_obj_set_align( cui_DeleteControlBtn, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_add_flag( cui_DeleteControlBtn, LV_OBJ_FLAG_IGNORE_LAYOUT | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( cui_DeleteControlBtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(cui_DeleteControlBtn, lv_color_hex(0xEE205A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_DeleteControlBtn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_Label32;
cui_Label32 = lv_label_create(cui_DeleteControlBtn);
lv_obj_set_width( cui_Label32, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_Label32, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_Label32, LV_ALIGN_CENTER );
lv_label_set_text(cui_Label32,"Delete");

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_CONTROLITEM_NUM);
children[UI_COMP_CONTROLITEM_CONTROLITEM] = cui_ControlItem;
children[UI_COMP_CONTROLITEM_CONTROLPANEL] = cui_ControlPanel;
children[UI_COMP_CONTROLITEM_CONTROLPANEL_GUARDPANEL] = cui_GuardPanel;
children[UI_COMP_CONTROLITEM_CONTROLPANEL_GUARDPANEL_LABEL28] = cui_Label28;
children[UI_COMP_CONTROLITEM_CONTROLPANEL_GUARDPANEL_GUARDOK] = cui_GuardOk;
children[UI_COMP_CONTROLITEM_CONTROLPANEL_DISARMPANEL] = cui_DisarmPanel;
children[UI_COMP_CONTROLITEM_CONTROLPANEL_DISARMPANEL_LABEL29] = cui_Label29;
children[UI_COMP_CONTROLITEM_CONTROLPANEL_DISARMPANEL_DISARMOK] = cui_DisarmOk;
children[UI_COMP_CONTROLITEM_CONTROLPANEL_MUTEPANEL] = cui_MutePanel;
children[UI_COMP_CONTROLITEM_CONTROLPANEL_MUTEPANEL_LABEL30] = cui_Label30;
children[UI_COMP_CONTROLITEM_CONTROLPANEL_MUTEPANEL_MUTEOK] = cui_MuteOk;
children[UI_COMP_CONTROLITEM_CONTROLPANEL_ALARMPANEL] = cui_AlarmPanel;
children[UI_COMP_CONTROLITEM_CONTROLPANEL_ALARMPANEL_LABEL31] = cui_Label31;
children[UI_COMP_CONTROLITEM_CONTROLPANEL_ALARMPANEL_ALARMOK] = cui_AlarmOk;
children[UI_COMP_CONTROLITEM_CONTROLPANEL_CONTROLID] = cui_controlId;
children[UI_COMP_CONTROLITEM_CONTROLPANEL_DELETECONTROLBTN] = cui_DeleteControlBtn;
children[UI_COMP_CONTROLITEM_CONTROLPANEL_DELETECONTROLBTN_LABEL32] = cui_Label32;
lv_obj_add_event_cb(cui_ControlItem, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_ControlItem, del_component_child_event_cb, LV_EVENT_DELETE, children);
lv_obj_add_event_cb(cui_GuardPanel, ui_event_comp_ControlItem_GuardPanel, LV_EVENT_ALL, children);
lv_obj_add_event_cb(cui_DisarmPanel, ui_event_comp_ControlItem_DisarmPanel, LV_EVENT_ALL, children);
lv_obj_add_event_cb(cui_MutePanel, ui_event_comp_ControlItem_MutePanel, LV_EVENT_ALL, children);
lv_obj_add_event_cb(cui_AlarmPanel, ui_event_comp_ControlItem_AlarmPanel, LV_EVENT_ALL, children);
lv_obj_add_event_cb(cui_DeleteControlBtn, ui_event_comp_ControlItem_DeleteControlBtn, LV_EVENT_ALL, children);
ui_comp_ControlItem_create_hook(cui_ControlItem);
return cui_ControlItem; 
}

