// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void unlockSystem(lv_event_t * e);
void loadDataInMain(lv_event_t * e);
void lockSystem(lv_event_t * e);
void loadMqttSettings(lv_event_t * e);
void saveMqttSettings(lv_event_t * e);
void loadFiWiSettings(lv_event_t * e);
void saveWifiSettings(lv_event_t * e);
void loadAllSensors(lv_event_t * e);
void startScan(lv_event_t * e);
void clearSensorsScreen(lv_event_t * e);
void stopScan(lv_event_t * e);
void loadSensor(lv_event_t * e);
void saveSensorSettings(lv_event_t * e);
void loadGeneralSettings(lv_event_t * e);
void saveGeneralSettings(lv_event_t * e);
void loadAllControls(lv_event_t * e);
void clearControlsScreen(lv_event_t * e);
void addControl(lv_event_t * e);
void addControlAction(lv_event_t * e);
void deleteControl(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
